// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO66ghv_1bYFpxcoBcLG_K0_iQE1cUzCw',
    appId: '1:453759948421:web:9d41228474fc311e4a3bec',
    messagingSenderId: '453759948421',
    projectId: 'chat-app-34dbc',
    authDomain: 'chat-app-34dbc.firebaseapp.com',
    storageBucket: 'chat-app-34dbc.appspot.com',
    measurementId: 'G-4XRJ6SZSBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDroVMv-7hTRwhD_n43iBDUnIlvCpGPTQ',
    appId: '1:453759948421:android:8e9ee8c96fb2cbbe4a3bec',
    messagingSenderId: '453759948421',
    projectId: 'chat-app-34dbc',
    storageBucket: 'chat-app-34dbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs2td1HVc8XgGupgNCImYZKerDBfrDCaI',
    appId: '1:453759948421:ios:809b845553de84724a3bec',
    messagingSenderId: '453759948421',
    projectId: 'chat-app-34dbc',
    storageBucket: 'chat-app-34dbc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs2td1HVc8XgGupgNCImYZKerDBfrDCaI',
    appId: '1:453759948421:ios:809b845553de84724a3bec',
    messagingSenderId: '453759948421',
    projectId: 'chat-app-34dbc',
    storageBucket: 'chat-app-34dbc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO66ghv_1bYFpxcoBcLG_K0_iQE1cUzCw',
    appId: '1:453759948421:web:9494a3d871469fbc4a3bec',
    messagingSenderId: '453759948421',
    projectId: 'chat-app-34dbc',
    authDomain: 'chat-app-34dbc.firebaseapp.com',
    storageBucket: 'chat-app-34dbc.appspot.com',
    measurementId: 'G-EC9G1S9R39',
  );

}